'use strict'
const acciones = [
    "Saltando", "Corriendo", "Bailando", "Cantando", "Gritando", "Riendo", "Llorando", "Pensando", "Durmiendo", "Soñando",
    "Volando", "Nadando", "Esquiando", "Surfando", "MontandoEnBici", "Cocinando", "Comiendo", "Bebiendo", "Hablando", "Leyendo",
    "Escribiendo", "Dibujando", "Pintando", "TocandoGuitarra", "TocandoPiano", "TocandoViolin", "jugandoFutbol", "jugandoBasket",
    "Meditando", "Trabajando", "Estudiando", "Investigando", "Explorando", "Inventando", "Cazando", "Pescando", "Conduciendo", "Programando",
    "Hackeando", "Editando", "Filmando", "Fotografiando", "Caminando", "Corriendo", "Saltando", "Boxeando", "Peleando", "Luchando",
    "Saludando", "Despidiéndose", "Besando", "Abrazando", "Cuidando", "Sanando", "Curando", "Ayudando", "Rescatando", "Protegiendo",
    "Observando", "Contemplando", "Admirando", "Aplaudiendo", "Festejando", "Celebrando", "Organizando", "Planeando", "Construyendo", "Destruyendo",
    "Reparando", "Arreglando", "Limpiando", "Ordenando", "Decorando", "Pintando", "Escribiendo", "Canturreando", "Tarareando", "Silbando",
    "EscuchandoMúsica", "Cocinando", "ProbandoComida", "Relajándose", "TomandoElSol", "Conversando", "ContandoChistes", "Trotando", "LevantandoPesas", "HaciendoYoga",
    "JugandoAJedrez", "JugandoAVideojuegos", "Viajando", "MontandoEnBicicleta", "Esquiando", "Buceando",  "PracticarandoParkour", "JugandoAlPingPong","JugandoConLaPlay",
    "MontandoAPatineta", "MontandoAMoto", "MontandoACaballo", "Esculpiendo", "Fotografiando", "Filmando", "DibujandoGraffitis", "Contemplando", "Cazando", "Pastoreando",
    "Cargando", "Reparando", "Programando", "Hackeando", "Modelando", "Observando", "Apuntando", "Bloqueando", "Destruyendo", "Arreglando",
    "SaltandoALaComba", "SorteandoObstáculos", "Balanceándose", "JugandoAlaRayuela", "LanzandoElBumerán", "Pateando", "SubiendoMontañas", "JugandoConLegos", "LanzandoDardos", "JugandoConGlobos",
    "PintandoUnCuadro", "EscribiendoUnLibro", "GrabandoUnPodcast", "CreandoUnaApp", "ConstruyendoUnRobot", "DiseñandoRopa", "HaciendoMagia", "AprendiendoIdiomas", "JugandoConMascotas", "LeyendoComics",
    "JugandoCartas", "HaciendoTíteres", "PintandoMandalas", "HaciendoOrigami", "ConstruyendoCastillosDeArena", "ModelandoArcilla", "CultivandoPlantas", "CocinandoGalletas", "TomandoCerveza", "HaciendoVino",
    "PreparandoCafé", "JugandoConGlobosDeAgua", "JugandoConBurbujeas", "DecorandoPasteles", "FotografiandoFlores", "PintandoPiedras", "CosechandoVerduras", "HaciendoJabones", "Cociendo", "Bordando",
    "Tejiendo", "HaciendoCrochet", "RestaurandoMuebles", "PintandoMuebles", "HaciendoBisutería", "DiseñandoJardines", "CazandoMariposas", "JugandoConMuñecas", "JugandoConCarros", "PintandoConLosDedos",
    "HaciendoCollages", "DiseñandoJoyas", "PintandoMandalas", "HaciendoCosplay", "HaciendoReciclajeCreativo", "ConstruyendoModelosAeronáuticos", "PintandoConAcuarelas", "OrganizandoFiestas", "PreparandoComidas", "HaciendoManualidades",
    "EscribiendoPoesía", "TocandoFlauta", "DibujandoCaricaturas", "CantandoOpera", "JugandoAjedrez", "DibujandoCómics", "ModelandoEsculturas", "FotografiandoPaisajes", "EditandoFotos", "HaciendoMúsicaElectrónica",
    "BailandoHipHop", "TocandoSaxofón", "JugandoBéisbol", "JugandoRugby", "JugandoBalonmano", "JugandoTenis", "JugandoBádminton", "JugandoGolf", "JugandoHockey", "JugandoCricket",
    "JugandoVoleibol", "JugandoFútbolAmericano", "HaciendoLacrosse", "HaciendoSoftball", "JugandoWaterpolo", "HaciendoBoxeo", "HaciendoJudo", "HaciendoKarate", "HaciendoTaekwondo", "HaciendoAikido",
    "HaciendoEsgrima", "HaciendoLuchaLibre", "HaciendoSumo", "HaciendoKendo", "HaciendoKickboxing", "HaciendoCapoeira", "HaciendoBoxeoTailandés", "HaciendoJiuJitsu",
    "HaciendoKungFu","HaciendoZumba", "HaciendoWrestling", "HaciendoGimnasia", "HaciendoDanza", "HaciendoBallet", "HaciendoJazz", "HaciendoFlamenco",
    "HaciendoTango", "HaciendoSalsa", "HaciendoMerengue", "BailandoBachata", "HaciendoZumba", "HaciendoAerobics", "HaciendoPilates", "HaciendoCrossfit", "HaciendoCalistenia", "HaciendoFitness",
    "HaciendoStrongman", "HaciendoPowerlifting", "HaciendoBodybuilding", "HaciendoStreching", "HaciendoCardio", "HaciendoSpinning", "HaciendoSteps", "HaciendoTabata",
    "HaciendoJumping", "HaciendoAquaFitness", "HaciendoAquaGym", "HaciendoAquaZumba", "HaciendoAquaAerobics", "HaciendoYogaAéreo", "HaciendoYogaCaliente", "HaciendoMeditación", "HaciendoYogaDanza",
    "HaciendoYogaFlow", "HaciendoYogaPower", "HaciendoYogaVinyasa", "HaciendoYogaKundalini", "HaciendoYogaAshtanga", "HaciendoYogaIyengar", "HaciendoYogaSivananda", "HaciendoYogaJivamukti", "HaciendoYogaNidra", "HaciendoYogaTantra",
    "HaciendoYogaChakras", "HaciendoYogaAyurveda", "HaciendoTherapia", "HaciendoMasajes", "HaciendoReflexología", "HaciendoAromaterapia", "HaciendoAcupuntura", "HaciendoFitoterapia", "HaciendoNaturopatía", "HaciendoHomeopatía", "HaciendoOsteopatía", "HaciendoReiki", "HaciendoBiomecánica", "HaciendoMusicoterapia", "MinandoBlockchain","HaciendoDanzaterapia", "HaciendoRisoterapia"]
