'use strict'
const sustantivos = [
    "Gato", "Ninja", "Pirata", "Perro", "Robot", "Zombie", "Vikingo", "Dragón",
    "Unicornio", "Marciano", "Mago", "Fantasma", "Caballero", "Hámster", "Dinosaurio", "Guerrero", "León", "Mono", "Vampiro",
    "Payaso", "Camaleón", "Tiburón", "Pingüino", "Lagarto", "Koala", "Elefante", "Zorro", "Oso", "Conejo",
    "Héroe", "Alien", "Ángel", "Murciélago", "Canguro", "Cocodrilo", "Gorila", "Hipopótamo", "Jaguar", "Leopardo",
    "Mapache", "Orangután", "Panda", "Rinoceronte", "Tigre", "Toro", "Vampiro", "Llama", "Pato",
    "Búho", "Cisne", "Delfín", "Erizo", "Ganso",
    "Jabalí", "Lemur", "Lince", "Lobo", "Mamut", "Pavo",
    "Perezoso", "Pulpo", "Ratón", "Reno", "Saltamontes", "Sapo", "Suricata", "Topo",
    "Tritón", "Wombat",  "Bisonte",
    "Buitre", "Burro", "Cacatúa", "Camarón", "Cangrejo", "Castor", "Ciervo", "Colibrí", "Cuervo", "Dromedario", "Emú", "Escorpión", "Flamenco", "GatoMontés",
    "Gorrión", "Halcón", "Hurón", "Loro", "Mejillón", "Mosquito", "Ornitorrinco", "Pelícano", "PezEspada", "Puma",
    "Quetzal", "Tapir", 
    "Tucán", "Venado", "Zorrillo", "Ñu", "Ratón", "OsoHormiguero", "Chita", "Guacamayo", "Albatro", "Buho", "Gallo", "PavoReal", "Cóndor",
    "PezPayaso",  "CaballitoDeMar", "ErizoDeMar", "Escarabajo",
    "Grillo", "Ciempiés", "Chinche", "Piojo", 
    "CaracolDeMar", "Caracol",  "Coral", "Plankton", "Crustáceo", "Pólipo",
    "Salmonete", "Atún", "Bacalao", "Rodaballo", "Lenguado",
    "Boquerón", "Esturión",  "Mero", "Perca", "Besugo", "Rape", "PezSanPedro",
    "Gaviotín", "Ibis", "Alcatraz",  "Porcino", "Cangrejo",  "Cernícalo", "Humanoide", "Cisne", "Gorrión", "Hércules", "Carpintero", "Avestruz", "Monstruo",
    "Fantasma",
    "Duende",
    "Extraterrestre",
    "Payaso",
    "Superhéroe",
    "Villano",
    "Genio",
    "Mago",
    "Esqueleto",
    "Zombi",
    "Yeti",
    "Mutante",
    "Alienígena",
    "Cíclope",
    "Gárgola",
    "Troll",
    "Gremlin",
    "Demonio",
    "MonstruoDeLasGalletas",
    "ElAbominableHombreDeLasNieves",
    "HombreInvisible",
    "HombreLobo",
    "GalletaDeJengibre"
]